### ISSUE TITLE
How to use controller support in devilutionX

### ISSUE THREAD

**Issue by neuromancer** [erfg12/devilution#2]
Hi,

I saw that you added instructions on how to compile this using Visual Studio. I wonder if the controller support could be extended to devilutionX as well.

**Comment by erfg12** [comment]
I'm working on fixing up Devilution-NX https://github.com/erfg12/devilution-nx

**Comment by neuromancer** [comment]
Neat!, let me know if you need testing.

**Comment by erfg12** [comment]
It's now in devilution-X thanks to everyone converting my DirectX code to OpenGL.
