### ISSUE TITLE
i was able to get it to work BUT

### ISSUE THREAD

**Issue by Sageskully** [erfg12/devilution#3]
how do i make it work with Tchernobog multiplayer id love to play this with my brother and not have to use keyboard and mouse due to my set up not being M&K friendly please help me out i have no idea what 4 new files have been added that have the new code in them, plrctrls.cpp/.h and joystick.cpp/.h
Any code that was altered in the other files were commented with // JAKE means

**Comment by erfg12** [comment]
idk how complicated they made their mod or even if it's open source lol.
